-- ==================================================
-- ESTRUCTURA COMPLETA DE BASE DE DATOS
-- ==================================================

DROP TABLE IF EXISTS Foto_Registro;
DROP TABLE IF EXISTS Datos_Campo_Medicion;
DROP TABLE IF EXISTS Datos_Campo;
DROP TABLE IF EXISTS Datos_Cosecha;
DROP TABLE IF EXISTS Momento_Evaluacion;
DROP TABLE IF EXISTS Parcela;
DROP TABLE IF EXISTS Bloque;
DROP TABLE IF EXISTS Tipo_Ensayo_EvaluacionDia;
DROP TABLE IF EXISTS Tipo_Ensayo_Variable;
DROP TABLE IF EXISTS Tipo_Ensayo;
DROP TABLE IF EXISTS Tratamiento_Producto;
DROP TABLE IF EXISTS Tratamiento;
DROP TABLE IF EXISTS Aplicacion;
DROP TABLE IF EXISTS Ensayo;
DROP TABLE IF EXISTS Protocolo_Variable;
DROP TABLE IF EXISTS Producto;
DROP TABLE IF EXISTS Laboratorio;
DROP TABLE IF EXISTS Usuario_Laboratorio;
DROP TABLE IF EXISTS Cultivo_Variedad;
DROP TABLE IF EXISTS Cultivo;
DROP TABLE IF EXISTS Usuario;
DROP TABLE IF EXISTS Rol;

-- TABLA ROL
CREATE TABLE Rol (rol_id INT AUTO_INCREMENT PRIMARY KEY, nombre_rol VARCHAR(50) NOT NULL UNIQUE, descripcion TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA USUARIO
CREATE TABLE Usuario (usuario_id INT AUTO_INCREMENT PRIMARY KEY, rol_id_fk INT NOT NULL, username VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, nombre VARCHAR(100) NULL, apellido VARCHAR(100) NULL, telefono VARCHAR(50) NULL, fecha_nacimiento DATE NULL, esta_activo BOOLEAN DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (rol_id_fk) REFERENCES Rol(rol_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA CULTIVO
CREATE TABLE Cultivo (cultivo_id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA CULTIVO_VARIEDAD
CREATE TABLE Cultivo_Variedad (variedad_id INT AUTO_INCREMENT PRIMARY KEY, cultivo_id_fk INT NOT NULL, nombre VARCHAR(150) NOT NULL, FOREIGN KEY (cultivo_id_fk) REFERENCES Cultivo(cultivo_id) ON DELETE CASCADE, UNIQUE(cultivo_id_fk, nombre)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA PROTOCOLO_VARIABLE
CREATE TABLE Protocolo_Variable (variable_id INT AUTO_INCREMENT PRIMARY KEY, nombre_variable VARCHAR(100) NOT NULL UNIQUE, unidad_medida VARCHAR(30) NULL, descripcion TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA TIPO_ENSAYO
CREATE TABLE Tipo_Ensayo (tipo_ensayo_id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(120) NOT NULL UNIQUE, evaluacion_csv VARCHAR(255) NULL, activo BOOLEAN NOT NULL DEFAULT TRUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA TIPO_ENSAYO_VARIABLE
CREATE TABLE Tipo_Ensayo_Variable (tipo_ensayo_variable_id INT AUTO_INCREMENT PRIMARY KEY, tipo_ensayo_id_fk INT NOT NULL, variable_id_fk INT NOT NULL, orden INT NULL, requerido BOOLEAN NOT NULL DEFAULT FALSE, unidad_override VARCHAR(30) NULL, escala VARCHAR(50) NULL, rango_min DECIMAL(10,2) NULL, rango_max DECIMAL(10,2) NULL, FOREIGN KEY (tipo_ensayo_id_fk) REFERENCES Tipo_Ensayo(tipo_ensayo_id) ON DELETE CASCADE, FOREIGN KEY (variable_id_fk) REFERENCES Protocolo_Variable(variable_id) ON DELETE CASCADE, UNIQUE(tipo_ensayo_id_fk, variable_id_fk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA TIPO_ENSAYO_EVALUACION_DIA
CREATE TABLE Tipo_Ensayo_EvaluacionDia (tipo_eval_dia_id INT AUTO_INCREMENT PRIMARY KEY, tipo_ensayo_id_fk INT NOT NULL, dia INT NOT NULL, FOREIGN KEY (tipo_ensayo_id_fk) REFERENCES Tipo_Ensayo(tipo_ensayo_id) ON DELETE CASCADE, UNIQUE(tipo_ensayo_id_fk, dia)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA LABORATORIO
CREATE TABLE Laboratorio (lab_id INT AUTO_INCREMENT PRIMARY KEY, nombre VARCHAR(100) NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA PRODUCTO
CREATE TABLE Producto (producto_id INT AUTO_INCREMENT PRIMARY KEY, lab_id_fk INT, nombre_comercial VARCHAR(100) NOT NULL, principio_activo VARCHAR(255), formulacion VARCHAR(50), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (lab_id_fk) REFERENCES Laboratorio(lab_id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA USUARIO_LABORATORIO
CREATE TABLE Usuario_Laboratorio (usuario_lab_id INT AUTO_INCREMENT PRIMARY KEY, usuario_id_fk INT NOT NULL, lab_id_fk INT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (usuario_id_fk) REFERENCES Usuario(usuario_id) ON DELETE CASCADE, FOREIGN KEY (lab_id_fk) REFERENCES Laboratorio(lab_id) ON DELETE CASCADE, UNIQUE(usuario_id_fk, lab_id_fk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA ENSAYO
CREATE TABLE Ensayo (ensayo_id INT AUTO_INCREMENT PRIMARY KEY, lab_id_fk INT NULL, nombre_ensayo VARCHAR(255) NOT NULL, codigo_labor VARCHAR(50) NULL, version_protocolo VARCHAR(20), tipo_ensayo_id_fk INT NULL, responsable VARCHAR(100), provincia VARCHAR(100), departamento VARCHAR(100), establecimiento VARCHAR(100), lote VARCHAR(50), latitud DECIMAL(10, 8), longitud DECIMAL(11, 8), cultivo_especie VARCHAR(100), cultivo_variedad VARCHAR(100), tipo_siembra VARCHAR(50), dist_surcos_cm DECIMAL(5, 2), fecha_siembra DATE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (lab_id_fk) REFERENCES Laboratorio(lab_id) ON DELETE SET NULL, FOREIGN KEY (tipo_ensayo_id_fk) REFERENCES Tipo_Ensayo(tipo_ensayo_id) ON DELETE SET NULL, UNIQUE(nombre_ensayo, version_protocolo), UNIQUE KEY uq_ensayo_lab_codigo (lab_id_fk, codigo_labor)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA APLICACION
CREATE TABLE Aplicacion (aplicacion_id INT AUTO_INCREMENT PRIMARY KEY, ensayo_id_fk INT NOT NULL, nombre_aplicacion VARCHAR(100) DEFAULT 'Primera aplicación', fecha_hora DATETIME, estadio_cultivo VARCHAR(50), temp_c DECIMAL(4, 1), humedad_pct DECIMAL(4, 1), viento_kmh DECIMAL(4, 1), equipo_info VARCHAR(255), pico_info VARCHAR(100), presion_bar DECIMAL(4, 2), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (ensayo_id_fk) REFERENCES Ensayo(ensayo_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA TRATAMIENTO
CREATE TABLE Tratamiento (tratamiento_id INT AUTO_INCREMENT PRIMARY KEY, ensayo_id_fk INT NOT NULL, numero_trat INT NOT NULL, descripcion TEXT, es_testigo BOOLEAN DEFAULT FALSE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (ensayo_id_fk) REFERENCES Ensayo(ensayo_id) ON DELETE CASCADE, UNIQUE(ensayo_id_fk, numero_trat)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA TRATAMIENTO_PRODUCTO
CREATE TABLE Tratamiento_Producto (trat_prod_id INT AUTO_INCREMENT PRIMARY KEY, tratamiento_id_fk INT NOT NULL, producto_id_fk INT NOT NULL, dosis VARCHAR(50), unidad_dosis VARCHAR(20) DEFAULT 'cc/ha', created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (tratamiento_id_fk) REFERENCES Tratamiento(tratamiento_id) ON DELETE CASCADE, FOREIGN KEY (producto_id_fk) REFERENCES Producto(producto_id) ON DELETE CASCADE, UNIQUE(tratamiento_id_fk, producto_id_fk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA BLOQUE
CREATE TABLE Bloque (bloque_id INT AUTO_INCREMENT PRIMARY KEY, ensayo_id_fk INT NOT NULL, nombre_bloque VARCHAR(10) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (ensayo_id_fk) REFERENCES Ensayo(ensayo_id) ON DELETE CASCADE, UNIQUE(ensayo_id_fk, nombre_bloque)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA PARCELA
CREATE TABLE Parcela (parcela_id INT AUTO_INCREMENT PRIMARY KEY, ensayo_id_fk INT NOT NULL, bloque_id_fk INT NOT NULL, tratamiento_id_fk INT NOT NULL, nombre_parcela VARCHAR(50) NULL, pos_x_grid INT, pos_y_grid INT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (ensayo_id_fk) REFERENCES Ensayo(ensayo_id) ON DELETE CASCADE, FOREIGN KEY (bloque_id_fk) REFERENCES Bloque(bloque_id) ON DELETE CASCADE, FOREIGN KEY (tratamiento_id_fk) REFERENCES Tratamiento(tratamiento_id) ON DELETE CASCADE, UNIQUE(bloque_id_fk, tratamiento_id_fk), UNIQUE KEY uq_parcela_ensayo_nombre (ensayo_id_fk, nombre_parcela)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA MOMENTO_EVALUACION
CREATE TABLE Momento_Evaluacion (momento_id INT AUTO_INCREMENT PRIMARY KEY, aplicacion_id_fk INT NOT NULL, nombre_momento VARCHAR(50) NOT NULL, dias_despues_aplicacion INT, fecha_evaluacion DATE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (aplicacion_id_fk) REFERENCES Aplicacion(aplicacion_id) ON DELETE CASCADE, UNIQUE(aplicacion_id_fk, nombre_momento)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA DATOS_CAMPO
CREATE TABLE Datos_Campo (dato_campo_id INT AUTO_INCREMENT PRIMARY KEY, parcela_id_fk INT NOT NULL, momento_id_fk INT NOT NULL, observaciones TEXT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (parcela_id_fk) REFERENCES Parcela(parcela_id) ON DELETE CASCADE, FOREIGN KEY (momento_id_fk) REFERENCES Momento_Evaluacion(momento_id) ON DELETE CASCADE, UNIQUE(parcela_id_fk, momento_id_fk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA DATOS_CAMPO_MEDICION
CREATE TABLE Datos_Campo_Medicion (medicion_id INT AUTO_INCREMENT PRIMARY KEY, dato_campo_id_fk INT NOT NULL, variable_id_fk INT NOT NULL, valor VARCHAR(255) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (dato_campo_id_fk) REFERENCES Datos_Campo(dato_campo_id) ON DELETE CASCADE, FOREIGN KEY (variable_id_fk) REFERENCES Protocolo_Variable(variable_id) ON DELETE CASCADE, UNIQUE(dato_campo_id_fk, variable_id_fk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA FOTO_REGISTRO
CREATE TABLE Foto_Registro (foto_id INT AUTO_INCREMENT PRIMARY KEY, dato_campo_id_fk INT NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, mime_type VARCHAR(100) NULL, fecha_subida TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (dato_campo_id_fk) REFERENCES Datos_Campo(dato_campo_id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TABLA DATOS_COSECHA
CREATE TABLE Datos_Cosecha (cosecha_id INT AUTO_INCREMENT PRIMARY KEY, parcela_id_fk INT NOT NULL, fecha_cosecha DATE, humedad_pct DECIMAL(5, 2), kg_ha_corregido DECIMAL(10, 2), gie DECIMAL(10, 2), observaciones TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (parcela_id_fk) REFERENCES Parcela(parcela_id) ON DELETE CASCADE, UNIQUE(parcela_id_fk)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

